// Candidate emoji: side-view whole bodies. Codepoint -> [id, description Jev sees, plan].
// Only entries that survive the auto-rig check in build-rigs.mjs reach the game.
export const CANDIDATES = [
  ["1f988", "shark", "a shark, megalodon or other big predatory fish", "fish"],
  ["1f40b", "whale", "a whale", "fish"],
  ["1f42c", "dolphin", "a dolphin or porpoise", "fish"],
  ["1f41f", "fish", "an ordinary fish, like a tuna, cod or trout", "fish"],
  ["1f420", "tropical_fish", "a small colourful tropical fish or piranha", "fish"],
  ["1f405", "tiger", "a tiger", "quadruped"],
  ["1f406", "leopard", "a leopard, cheetah, jaguar or other spotted big cat", "quadruped"],
  ["1f40e", "horse", "a horse or pony", "quadruped"],
  ["1f993", "zebra", "a zebra", "quadruped"],
  ["1f98c", "deer", "a deer, moose or elk", "quadruped"],
  ["1f402", "ox", "an ox, bull or bison", "quadruped"],
  ["1f403", "water_buffalo", "a water buffalo", "quadruped"],
  ["1f404", "cow", "a cow", "quadruped"],
  ["1f416", "pig", "a pig", "quadruped"],
  ["1f417", "boar", "a wild boar or warthog", "quadruped"],
  ["1f40f", "ram", "a ram or sheep with curled horns", "quadruped"],
  ["1f411", "sheep", "a sheep or lamb", "quadruped"],
  ["1f410", "goat", "a goat", "quadruped"],
  ["1f42a", "camel", "a camel", "quadruped"],
  ["1f999", "llama", "a llama or alpaca", "quadruped"],
  ["1f992", "giraffe", "a giraffe", "quadruped"],
  ["1f418", "elephant", "an elephant", "quadruped"],
  ["1f9a3", "mammoth", "a mammoth", "quadruped"],
  ["1f98f", "rhino", "a rhinoceros", "quadruped"],
  ["1f99b", "hippo", "a hippopotamus", "quadruped"],
  ["1f401", "mouse", "a mouse", "quadruped"],
  ["1f400", "rat", "a rat", "quadruped"],
  ["1f407", "rabbit", "a rabbit or hare", "quadruped"],
  ["1f43f", "chipmunk", "a squirrel or chipmunk", "quadruped"],
  ["1f9ab", "beaver", "a beaver", "quadruped"],
  ["1f994", "hedgehog", "a hedgehog or porcupine", "quadruped"],
  ["1f9a8", "skunk", "a skunk", "quadruped"],
  ["1f9a1", "badger", "a badger or honey badger", "quadruped"],
  ["1f422", "turtle", "a turtle or tortoise", "quadruped"],
  ["1f995", "sauropod", "a long-necked dinosaur like a brachiosaurus", "quadruped"],
  ["1f996", "t_rex", "a T-rex or other big two-legged dinosaur", "quadruped"],
  ["1f413", "rooster", "a rooster or chicken", "bird"],
  ["1f983", "turkey", "a turkey", "bird"],
  ["1f986", "duck", "a duck", "bird"],
  ["1f9a2", "swan", "a swan or goose", "bird"],
  ["1f9a9", "flamingo", "a flamingo", "bird"],
  ["1f9a4", "dodo", "a dodo", "bird"],
  ["1f427", "penguin", "a penguin", "bird"],
  ["1f40c", "snail", "a snail or slug", "blob"],
  ["1f41b", "caterpillar", "a caterpillar or worm", "snake"],
  ["1f40d", "snake", "a snake", "snake"],
  ["1f41c", "ant", "an ant", "bug"],
  ["1f41e", "ladybug", "a ladybird or beetle", "bug"],
  ["1f997", "cricket", "a cricket or grasshopper", "bug"],
  ["1f982", "scorpion", "a scorpion", "bug"],
  ["1f980", "crab", "a crab", "bug"],
  ["1f99e", "lobster", "a lobster", "bug"],
  ["1f577", "spider", "a spider", "bug"],
  ["1f6d2", "trolley", "a shopping trolley or cart", "wheeled"],
  ["1f697", "car", "a car", "wheeled"],
  ["1f69c", "tractor", "a tractor", "wheeled"],
  ["1f6f5", "scooter", "a motor scooter or moped", "wheeled"],
  ["1f3ce", "race_car", "a racing car", "wheeled"],
  ["1f69a", "truck", "a delivery truck or lorry", "wheeled"],
];

// Audited by eye on the contact sheet (scripts/contact-sheet.mjs). Everything else faces left.
export const FACES_RIGHT = new Set(["cat", "dog", "ram", "mouse", "chipmunk", "beaver", "hedgehog", "scooter"]);
